//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ajWebSiteServices", ConfigurationName="MessageService.WsMobileSoap")]
    public interface WsMobileSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="ajWebSiteServices/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<MessageService.SendSMSResponse> SendSMSAsync(MessageService.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ajWebSiteServices/ACCORD", ReplyAction="*")]
        System.Threading.Tasks.Task<MessageService.ACCORDResponse> ACCORDAsync(MessageService.ACCORDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ajWebSiteServices/PAYROLL", ReplyAction="*")]
        System.Threading.Tasks.Task<MessageService.PAYROLLResponse> PAYROLLAsync(MessageService.PAYROLLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="ajWebSiteServices", Order=0)]
        public MessageService.SendSMSRequestBody Body;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(MessageService.SendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ajWebSiteServices")]
    public partial class SendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string smsText;
        
        public SendSMSRequestBody()
        {
        }
        
        public SendSMSRequestBody(string password, string Mobile, string smsText)
        {
            this.password = password;
            this.Mobile = Mobile;
            this.smsText = smsText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="ajWebSiteServices", Order=0)]
        public MessageService.SendSMSResponseBody Body;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(MessageService.SendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ajWebSiteServices")]
    public partial class SendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody()
        {
        }
        
        public SendSMSResponseBody(string SendSMSResult)
        {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ACCORDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ACCORD", Namespace="ajWebSiteServices", Order=0)]
        public MessageService.ACCORDRequestBody Body;
        
        public ACCORDRequest()
        {
        }
        
        public ACCORDRequest(MessageService.ACCORDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ajWebSiteServices")]
    public partial class ACCORDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PRMPERSONID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PRMDATEFLAG;
        
        public ACCORDRequestBody()
        {
        }
        
        public ACCORDRequestBody(string password, string PRMPERSONID, string PRMDATEFLAG)
        {
            this.password = password;
            this.PRMPERSONID = PRMPERSONID;
            this.PRMDATEFLAG = PRMDATEFLAG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ACCORDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ACCORDResponse", Namespace="ajWebSiteServices", Order=0)]
        public MessageService.ACCORDResponseBody Body;
        
        public ACCORDResponse()
        {
        }
        
        public ACCORDResponse(MessageService.ACCORDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ajWebSiteServices")]
    public partial class ACCORDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ACCORDResult;
        
        public ACCORDResponseBody()
        {
        }
        
        public ACCORDResponseBody(byte[] ACCORDResult)
        {
            this.ACCORDResult = ACCORDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PAYROLLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PAYROLL", Namespace="ajWebSiteServices", Order=0)]
        public MessageService.PAYROLLRequestBody Body;
        
        public PAYROLLRequest()
        {
        }
        
        public PAYROLLRequest(MessageService.PAYROLLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ajWebSiteServices")]
    public partial class PAYROLLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PRMPERSONID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PRMDATEFLAG;
        
        public PAYROLLRequestBody()
        {
        }
        
        public PAYROLLRequestBody(string password, string PRMPERSONID, string PRMDATEFLAG)
        {
            this.password = password;
            this.PRMPERSONID = PRMPERSONID;
            this.PRMDATEFLAG = PRMDATEFLAG;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PAYROLLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PAYROLLResponse", Namespace="ajWebSiteServices", Order=0)]
        public MessageService.PAYROLLResponseBody Body;
        
        public PAYROLLResponse()
        {
        }
        
        public PAYROLLResponse(MessageService.PAYROLLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ajWebSiteServices")]
    public partial class PAYROLLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] PAYROLLResult;
        
        public PAYROLLResponseBody()
        {
        }
        
        public PAYROLLResponseBody(byte[] PAYROLLResult)
        {
            this.PAYROLLResult = PAYROLLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WsMobileSoapChannel : MessageService.WsMobileSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WsMobileSoapClient : System.ServiceModel.ClientBase<MessageService.WsMobileSoap>, MessageService.WsMobileSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WsMobileSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WsMobileSoapClient.GetBindingForEndpoint(endpointConfiguration), WsMobileSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMobileSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WsMobileSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMobileSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WsMobileSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WsMobileSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageService.SendSMSResponse> MessageService.WsMobileSoap.SendSMSAsync(MessageService.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageService.SendSMSResponse> SendSMSAsync(string password, string Mobile, string smsText)
        {
            MessageService.SendSMSRequest inValue = new MessageService.SendSMSRequest();
            inValue.Body = new MessageService.SendSMSRequestBody();
            inValue.Body.password = password;
            inValue.Body.Mobile = Mobile;
            inValue.Body.smsText = smsText;
            return ((MessageService.WsMobileSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageService.ACCORDResponse> MessageService.WsMobileSoap.ACCORDAsync(MessageService.ACCORDRequest request)
        {
            return base.Channel.ACCORDAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageService.ACCORDResponse> ACCORDAsync(string password, string PRMPERSONID, string PRMDATEFLAG)
        {
            MessageService.ACCORDRequest inValue = new MessageService.ACCORDRequest();
            inValue.Body = new MessageService.ACCORDRequestBody();
            inValue.Body.password = password;
            inValue.Body.PRMPERSONID = PRMPERSONID;
            inValue.Body.PRMDATEFLAG = PRMDATEFLAG;
            return ((MessageService.WsMobileSoap)(this)).ACCORDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MessageService.PAYROLLResponse> MessageService.WsMobileSoap.PAYROLLAsync(MessageService.PAYROLLRequest request)
        {
            return base.Channel.PAYROLLAsync(request);
        }
        
        public System.Threading.Tasks.Task<MessageService.PAYROLLResponse> PAYROLLAsync(string password, string PRMPERSONID, string PRMDATEFLAG)
        {
            MessageService.PAYROLLRequest inValue = new MessageService.PAYROLLRequest();
            inValue.Body = new MessageService.PAYROLLRequestBody();
            inValue.Body.password = password;
            inValue.Body.PRMPERSONID = PRMPERSONID;
            inValue.Body.PRMDATEFLAG = PRMDATEFLAG;
            return ((MessageService.WsMobileSoap)(this)).PAYROLLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsMobileSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WsMobileSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WsMobileSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.ajWebSitecorp.ir/wspayroll/wsmobile.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WsMobileSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.ajWebSitecorp.ir/wspayroll/wsmobile.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WsMobileSoap,
            
            WsMobileSoap12,
        }
    }
}
